// <auto-generated />
namespace AquavitBEAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SongToReleaesInSongs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SongToReleaesInSongs));
        
        string IMigrationMetadata.Id
        {
            get { return "201702282022400_SongToReleaesInSongs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
